[tools]
chezmoi = "latest"
node = "lts"
perl = "5.40.1.0"
python = "3.13.2"
kubectl = "1.32.3"
uv = "0.6.12"
gcloud = "517.0.0"
java = "openjdk-21.0.2"
go = "1.24.2"
dotnet = "9.0.200"
rust = "stable"
direnv = "2.35.0"
lazygit = "latest"
